version: '3.4'

services:
  web:
    build: .
    container_name: "bookmyshow"
    restart: always    
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html/"

  #db:
    #platform: linux/x86_64
    #image: postgres:9.6
    #restart: always
    #environment: 
      #- POSTGRES_DB=bookmyshow
      #- POSTGRES_USER=postgres
      #- POSTGRES_PASSWORD=$srpago.123
    #ports:
      #- "5432:5432"
    #expose:
      #- "5432"
    #volumes:
      #- ./db:/var/lib/postgresql/data